defmodule AshSvelteApp.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:books) do
      modify :author, :text, null: false
      modify :title, :text, null: false
      modify :id, :uuid
    end
  end

  def down do
    alter table(:books) do
      modify :id, :uuid
      modify :title, :text, null: true
      modify :author, :text, null: true
    end
  end
end
