defmodule AshSvelteApp.Repo.Migrations.Initialize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:books, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :author, :text
      add :isbn, :text
    end
  end

  def down do
    drop table(:books)
  end
end
