defmodule AshSvelteApp.Repo.Migrations.AddBookTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:books) do
      modify :author, :text, null: false
      modify :title, :text, null: false
      modify :id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:books) do
      remove :updated_at
      remove :inserted_at
      modify :id, :uuid
      modify :title, :text, null: true
      modify :author, :text, null: true
    end
  end
end
